<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class HalamanDataTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('halaman_data')->delete();
        
        \DB::table('halaman_data')->insert(array (
            0 => 
            array (
                'id' => 1884,
                'tematik_id' => 7,
                'kelompok' => 'Target',
                'nakes' => 20,
                'petugas_publik' => 130,
                'lansia' => 30,
                'masyarakat_umum' => 376,
                'remaja' => 100,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 6,
                'usia' => 100,
            ),
            1 => 
            array (
                'id' => 1885,
                'tematik_id' => 7,
                'kelompok' => 'Target',
                'nakes' => 80,
                'petugas_publik' => 350,
                'lansia' => 140,
                'masyarakat_umum' => 2402,
                'remaja' => 400,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 9,
                'usia' => 400,
            ),
            2 => 
            array (
                'id' => 1886,
                'tematik_id' => 7,
                'kelompok' => 'Target',
                'nakes' => 35,
                'petugas_publik' => 220,
                'lansia' => 60,
                'masyarakat_umum' => 872,
                'remaja' => 200,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 8,
                'usia' => 200,
            ),
            3 => 
            array (
                'id' => 1887,
                'tematik_id' => 7,
                'kelompok' => 'Target',
                'nakes' => 52,
                'petugas_publik' => 270,
                'lansia' => 110,
                'masyarakat_umum' => 1645,
                'remaja' => 310,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 11,
                'usia' => 310,
            ),
            4 => 
            array (
                'id' => 1888,
                'tematik_id' => 7,
                'kelompok' => 'Target',
                'nakes' => 50,
                'petugas_publik' => 250,
                'lansia' => 100,
                'masyarakat_umum' => 1412,
                'remaja' => 290,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 14,
                'usia' => 290,
            ),
            5 => 
            array (
                'id' => 1889,
                'tematik_id' => 7,
                'kelompok' => 'Target',
                'nakes' => 90,
                'petugas_publik' => 370,
                'lansia' => 130,
                'masyarakat_umum' => 2150,
                'remaja' => 450,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 15,
                'usia' => 450,
            ),
            6 => 
            array (
                'id' => 1890,
                'tematik_id' => 7,
                'kelompok' => 'Target',
                'nakes' => 45,
                'petugas_publik' => 245,
                'lansia' => 90,
                'masyarakat_umum' => 980,
                'remaja' => 250,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 12,
                'usia' => 250,
            ),
            7 => 
            array (
                'id' => 1891,
                'tematik_id' => 7,
                'kelompok' => 'Target',
                'nakes' => 120,
                'petugas_publik' => 420,
                'lansia' => 160,
                'masyarakat_umum' => 2250,
                'remaja' => 500,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 13,
                'usia' => 500,
            ),
            8 => 
            array (
                'id' => 1892,
                'tematik_id' => 7,
                'kelompok' => 'Target',
                'nakes' => 62,
                'petugas_publik' => 275,
                'lansia' => 130,
                'masyarakat_umum' => 1618,
                'remaja' => 350,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 10,
                'usia' => 350,
            ),
            9 => 
            array (
                'id' => 1893,
                'tematik_id' => 8,
                'kelompok' => 'Target',
                'nakes' => 19,
                'petugas_publik' => 150,
                'lansia' => 70,
                'masyarakat_umum' => 876,
                'remaja' => 186,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 22,
                'usia' => 186,
            ),
            10 => 
            array (
                'id' => 1894,
                'tematik_id' => 8,
                'kelompok' => 'Target',
                'nakes' => 5,
                'petugas_publik' => 15,
                'lansia' => 45,
                'masyarakat_umum' => 196,
                'remaja' => 56,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 24,
                'usia' => 56,
            ),
            11 => 
            array (
                'id' => 1895,
                'tematik_id' => 8,
                'kelompok' => 'Target',
                'nakes' => 12,
                'petugas_publik' => 120,
                'lansia' => 50,
                'masyarakat_umum' => 382,
                'remaja' => 106,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 27,
                'usia' => 106,
            ),
            12 => 
            array (
                'id' => 1896,
                'tematik_id' => 8,
                'kelompok' => 'Target',
                'nakes' => 16,
                'petugas_publik' => 135,
                'lansia' => 52,
                'masyarakat_umum' => 461,
                'remaja' => 141,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 25,
                'usia' => 141,
            ),
            13 => 
            array (
                'id' => 1897,
                'tematik_id' => 8,
                'kelompok' => 'Target',
                'nakes' => 29,
                'petugas_publik' => 155,
                'lansia' => 82,
                'masyarakat_umum' => 1148,
                'remaja' => 246,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 26,
                'usia' => 246,
            ),
            14 => 
            array (
                'id' => 1898,
                'tematik_id' => 8,
                'kelompok' => 'Target',
                'nakes' => 26,
                'petugas_publik' => 154,
                'lansia' => 80,
                'masyarakat_umum' => 1009,
                'remaja' => 206,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 28,
                'usia' => 206,
            ),
            15 => 
            array (
                'id' => 1899,
                'tematik_id' => 8,
                'kelompok' => 'Target',
                'nakes' => 34,
                'petugas_publik' => 321,
                'lansia' => 105,
                'masyarakat_umum' => 2383,
                'remaja' => 426,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 23,
                'usia' => 426,
            ),
            16 => 
            array (
                'id' => 1900,
                'tematik_id' => 8,
                'kelompok' => 'Target',
                'nakes' => 31,
                'petugas_publik' => 165,
                'lansia' => 93,
                'masyarakat_umum' => 1264,
                'remaja' => 296,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 19,
                'usia' => 296,
            ),
            17 => 
            array (
                'id' => 1901,
                'tematik_id' => 8,
                'kelompok' => 'Target',
                'nakes' => 22,
                'petugas_publik' => 140,
                'lansia' => 59,
                'masyarakat_umum' => 854,
                'remaja' => 166,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 16,
                'usia' => 166,
            ),
            18 => 
            array (
                'id' => 1902,
                'tematik_id' => 8,
                'kelompok' => 'Target',
                'nakes' => 23,
                'petugas_publik' => 145,
                'lansia' => 64,
                'masyarakat_umum' => 949,
                'remaja' => 171,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 18,
                'usia' => 171,
            ),
            19 => 
            array (
                'id' => 1903,
                'tematik_id' => 9,
                'kelompok' => 'Target',
                'nakes' => 5,
                'petugas_publik' => 60,
                'lansia' => 30,
                'masyarakat_umum' => 734,
                'remaja' => 35,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 34,
                'usia' => 35,
            ),
            20 => 
            array (
                'id' => 1904,
                'tematik_id' => 9,
                'kelompok' => 'Target',
                'nakes' => 9,
                'petugas_publik' => 350,
                'lansia' => 70,
                'masyarakat_umum' => 636,
                'remaja' => 200,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 29,
                'usia' => 200,
            ),
            21 => 
            array (
                'id' => 1905,
                'tematik_id' => 9,
                'kelompok' => 'Target',
                'nakes' => 15,
                'petugas_publik' => 300,
                'lansia' => 80,
                'masyarakat_umum' => 827,
                'remaja' => 225,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 30,
                'usia' => 225,
            ),
            22 => 
            array (
                'id' => 1906,
                'tematik_id' => 9,
                'kelompok' => 'Target',
                'nakes' => 20,
                'petugas_publik' => 200,
                'lansia' => 100,
                'masyarakat_umum' => 1500,
                'remaja' => 245,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 20,
                'usia' => 245,
            ),
            23 => 
            array (
                'id' => 1907,
                'tematik_id' => 9,
                'kelompok' => 'Target',
                'nakes' => 25,
                'petugas_publik' => 200,
                'lansia' => 150,
                'masyarakat_umum' => 1776,
                'remaja' => 370,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 21,
                'usia' => 370,
            ),
            24 => 
            array (
                'id' => 1908,
                'tematik_id' => 9,
                'kelompok' => 'Target',
                'nakes' => 25,
                'petugas_publik' => 250,
                'lansia' => 150,
                'masyarakat_umum' => 1440,
                'remaja' => 350,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 31,
                'usia' => 350,
            ),
            25 => 
            array (
                'id' => 1909,
                'tematik_id' => 9,
                'kelompok' => 'Target',
                'nakes' => 20,
                'petugas_publik' => 250,
                'lansia' => 75,
                'masyarakat_umum' => 870,
                'remaja' => 180,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 17,
                'usia' => 180,
            ),
            26 => 
            array (
                'id' => 1910,
                'tematik_id' => 9,
                'kelompok' => 'Target',
                'nakes' => 27,
                'petugas_publik' => 1490,
                'lansia' => 180,
                'masyarakat_umum' => 2500,
                'remaja' => 530,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 32,
                'usia' => 530,
            ),
            27 => 
            array (
                'id' => 1911,
                'tematik_id' => 9,
                'kelompok' => 'Target',
                'nakes' => 35,
                'petugas_publik' => 1400,
                'lansia' => 265,
                'masyarakat_umum' => 4000,
                'remaja' => 865,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 33,
                'usia' => 865,
            ),
            28 => 
            array (
                'id' => 1912,
                'tematik_id' => 10,
                'kelompok' => 'Target',
                'nakes' => 253,
                'petugas_publik' => 743,
                'lansia' => 454,
                'masyarakat_umum' => 2373,
                'remaja' => 305,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 51,
                'usia' => 305,
            ),
            29 => 
            array (
                'id' => 1913,
                'tematik_id' => 10,
                'kelompok' => 'Target',
                'nakes' => 154,
                'petugas_publik' => 1118,
                'lansia' => 623,
                'masyarakat_umum' => 3622,
                'remaja' => 810,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 46,
                'usia' => 810,
            ),
            30 => 
            array (
                'id' => 1914,
                'tematik_id' => 10,
                'kelompok' => 'Target',
                'nakes' => 374,
                'petugas_publik' => 974,
                'lansia' => 455,
                'masyarakat_umum' => 2809,
                'remaja' => 590,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 43,
                'usia' => 590,
            ),
            31 => 
            array (
                'id' => 1915,
                'tematik_id' => 10,
                'kelompok' => 'Target',
                'nakes' => 354,
                'petugas_publik' => 924,
                'lansia' => 454,
                'masyarakat_umum' => 2774,
                'remaja' => 570,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 45,
                'usia' => 570,
            ),
            32 => 
            array (
                'id' => 1916,
                'tematik_id' => 10,
                'kelompok' => 'Target',
                'nakes' => 434,
                'petugas_publik' => 1043,
                'lansia' => 623,
                'masyarakat_umum' => 3265,
                'remaja' => 772,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 42,
                'usia' => 772,
            ),
            33 => 
            array (
                'id' => 1917,
                'tematik_id' => 10,
                'kelompok' => 'Target',
                'nakes' => 152,
                'petugas_publik' => 643,
                'lansia' => 118,
                'masyarakat_umum' => 1462,
                'remaja' => 250,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 44,
                'usia' => 250,
            ),
            34 => 
            array (
                'id' => 1918,
                'tematik_id' => 10,
                'kelompok' => 'Target',
                'nakes' => 454,
                'petugas_publik' => 1243,
                'lansia' => 455,
                'masyarakat_umum' => 3393,
                'remaja' => 838,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 41,
                'usia' => 838,
            ),
            35 => 
            array (
                'id' => 1919,
                'tematik_id' => 10,
                'kelompok' => 'Target',
                'nakes' => 154,
                'petugas_publik' => 1088,
                'lansia' => 455,
                'masyarakat_umum' => 2673,
                'remaja' => 600,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 50,
                'usia' => 600,
            ),
            36 => 
            array (
                'id' => 1920,
                'tematik_id' => 10,
                'kelompok' => 'Target',
                'nakes' => 384,
                'petugas_publik' => 1113,
                'lansia' => 455,
                'masyarakat_umum' => 2826,
                'remaja' => 628,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 49,
                'usia' => 628,
            ),
            37 => 
            array (
                'id' => 1921,
                'tematik_id' => 10,
                'kelompok' => 'Target',
                'nakes' => 202,
                'petugas_publik' => 688,
                'lansia' => 454,
                'masyarakat_umum' => 1064,
                'remaja' => 300,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 48,
                'usia' => 300,
            ),
            38 => 
            array (
                'id' => 1922,
                'tematik_id' => 10,
                'kelompok' => 'Target',
                'nakes' => 302,
                'petugas_publik' => 823,
                'lansia' => 454,
                'masyarakat_umum' => 2309,
                'remaja' => 380,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 47,
                'usia' => 380,
            ),
            39 => 
            array (
                'id' => 1923,
                'tematik_id' => 11,
                'kelompok' => 'Target',
                'nakes' => 10,
                'petugas_publik' => 700,
                'lansia' => 70,
                'masyarakat_umum' => 793,
                'remaja' => 167,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 38,
                'usia' => 167,
            ),
            40 => 
            array (
                'id' => 1924,
                'tematik_id' => 11,
                'kelompok' => 'Target',
                'nakes' => 14,
                'petugas_publik' => 950,
                'lansia' => 95,
                'masyarakat_umum' => 796,
                'remaja' => 167,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 39,
                'usia' => 167,
            ),
            41 => 
            array (
                'id' => 1925,
                'tematik_id' => 11,
                'kelompok' => 'Target',
                'nakes' => 6,
                'petugas_publik' => 580,
                'lansia' => 58,
                'masyarakat_umum' => 793,
                'remaja' => 166,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 37,
                'usia' => 166,
            ),
            42 => 
            array (
                'id' => 1926,
                'tematik_id' => 11,
                'kelompok' => 'Target',
                'nakes' => 8,
                'petugas_publik' => 600,
                'lansia' => 60,
                'masyarakat_umum' => 793,
                'remaja' => 167,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 40,
                'usia' => 167,
            ),
            43 => 
            array (
                'id' => 1927,
                'tematik_id' => 11,
                'kelompok' => 'Target',
                'nakes' => 9,
                'petugas_publik' => 650,
                'lansia' => 65,
                'masyarakat_umum' => 793,
                'remaja' => 167,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 35,
                'usia' => 167,
            ),
            44 => 
            array (
                'id' => 1928,
                'tematik_id' => 11,
                'kelompok' => 'Target',
                'nakes' => 4,
                'petugas_publik' => 520,
                'lansia' => 52,
                'masyarakat_umum' => 793,
                'remaja' => 166,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 36,
                'usia' => 166,
            ),
            45 => 
            array (
                'id' => 1929,
                'tematik_id' => 12,
                'kelompok' => 'Target',
                'nakes' => 4,
                'petugas_publik' => 39,
                'lansia' => 25,
                'masyarakat_umum' => 439,
                'remaja' => 55,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 54,
                'usia' => 55,
            ),
            46 => 
            array (
                'id' => 1930,
                'tematik_id' => 12,
                'kelompok' => 'Target',
                'nakes' => 12,
                'petugas_publik' => 51,
                'lansia' => 75,
                'masyarakat_umum' => 732,
                'remaja' => 275,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 52,
                'usia' => 275,
            ),
            47 => 
            array (
                'id' => 1931,
                'tematik_id' => 12,
                'kelompok' => 'Target',
                'nakes' => 11,
                'petugas_publik' => 71,
                'lansia' => 65,
                'masyarakat_umum' => 650,
                'remaja' => 189,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 57,
                'usia' => 189,
            ),
            48 => 
            array (
                'id' => 1932,
                'tematik_id' => 12,
                'kelompok' => 'Target',
                'nakes' => 10,
                'petugas_publik' => 45,
                'lansia' => 37,
                'masyarakat_umum' => 480,
                'remaja' => 65,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 53,
                'usia' => 65,
            ),
            49 => 
            array (
                'id' => 1933,
                'tematik_id' => 12,
                'kelompok' => 'Target',
                'nakes' => 2,
                'petugas_publik' => 15,
                'lansia' => 23,
                'masyarakat_umum' => 390,
                'remaja' => 45,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 55,
                'usia' => 45,
            ),
            50 => 
            array (
                'id' => 1934,
                'tematik_id' => 12,
                'kelompok' => 'Target',
                'nakes' => 9,
                'petugas_publik' => 50,
                'lansia' => 50,
                'masyarakat_umum' => 560,
                'remaja' => 90,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 59,
                'usia' => 90,
            ),
            51 => 
            array (
                'id' => 1935,
                'tematik_id' => 12,
                'kelompok' => 'Target',
                'nakes' => 3,
                'petugas_publik' => 30,
                'lansia' => 20,
                'masyarakat_umum' => 430,
                'remaja' => 111,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 58,
                'usia' => 111,
            ),
            52 => 
            array (
                'id' => 1936,
                'tematik_id' => 12,
                'kelompok' => 'Target',
                'nakes' => 5,
                'petugas_publik' => 44,
                'lansia' => 45,
                'masyarakat_umum' => 510,
                'remaja' => 70,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 56,
                'usia' => 70,
            ),
            53 => 
            array (
                'id' => 1937,
                'tematik_id' => 13,
                'kelompok' => 'Target',
                'nakes' => 119,
                'petugas_publik' => 183,
                'lansia' => 209,
                'masyarakat_umum' => 1190,
                'remaja' => 183,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 74,
                'usia' => 183,
            ),
            54 => 
            array (
                'id' => 1938,
                'tematik_id' => 13,
                'kelompok' => 'Target',
                'nakes' => 110,
                'petugas_publik' => 180,
                'lansia' => 208,
                'masyarakat_umum' => 1190,
                'remaja' => 180,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 61,
                'usia' => 180,
            ),
            55 => 
            array (
                'id' => 1939,
                'tematik_id' => 13,
                'kelompok' => 'Target',
                'nakes' => 45,
                'petugas_publik' => 119,
                'lansia' => 100,
                'masyarakat_umum' => 335,
                'remaja' => 119,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 67,
                'usia' => 119,
            ),
            56 => 
            array (
                'id' => 1940,
                'tematik_id' => 13,
                'kelompok' => 'Target',
                'nakes' => 108,
                'petugas_publik' => 174,
                'lansia' => 208,
                'masyarakat_umum' => 1190,
                'remaja' => 174,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 70,
                'usia' => 174,
            ),
            57 => 
            array (
                'id' => 1941,
                'tematik_id' => 13,
                'kelompok' => 'Target',
                'nakes' => 120,
                'petugas_publik' => 220,
                'lansia' => 208,
                'masyarakat_umum' => 1190,
                'remaja' => 220,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 66,
                'usia' => 220,
            ),
            58 => 
            array (
                'id' => 1942,
                'tematik_id' => 13,
                'kelompok' => 'Target',
                'nakes' => 127,
                'petugas_publik' => 525,
                'lansia' => 263,
                'masyarakat_umum' => 2046,
                'remaja' => 525,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 72,
                'usia' => 525,
            ),
            59 => 
            array (
                'id' => 1943,
                'tematik_id' => 13,
                'kelompok' => 'Target',
                'nakes' => 122,
                'petugas_publik' => 220,
                'lansia' => 209,
                'masyarakat_umum' => 1191,
                'remaja' => 220,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 71,
                'usia' => 220,
            ),
            60 => 
            array (
                'id' => 1944,
                'tematik_id' => 13,
                'kelompok' => 'Target',
                'nakes' => 120,
                'petugas_publik' => 255,
                'lansia' => 209,
                'masyarakat_umum' => 1190,
                'remaja' => 255,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 73,
                'usia' => 255,
            ),
            61 => 
            array (
                'id' => 1945,
                'tematik_id' => 13,
                'kelompok' => 'Target',
                'nakes' => 80,
                'petugas_publik' => 314,
                'lansia' => 208,
                'masyarakat_umum' => 1190,
                'remaja' => 314,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 63,
                'usia' => 314,
            ),
            62 => 
            array (
                'id' => 1946,
                'tematik_id' => 13,
                'kelompok' => 'Target',
                'nakes' => 109,
                'petugas_publik' => 145,
                'lansia' => 155,
                'masyarakat_umum' => 520,
                'remaja' => 145,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 68,
                'usia' => 145,
            ),
            63 => 
            array (
                'id' => 1947,
                'tematik_id' => 13,
                'kelompok' => 'Target',
                'nakes' => 124,
                'petugas_publik' => 425,
                'lansia' => 263,
                'masyarakat_umum' => 1526,
                'remaja' => 425,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 75,
                'usia' => 425,
            ),
            64 => 
            array (
                'id' => 1948,
                'tematik_id' => 13,
                'kelompok' => 'Target',
                'nakes' => 100,
                'petugas_publik' => 169,
                'lansia' => 208,
                'masyarakat_umum' => 1190,
                'remaja' => 169,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 65,
                'usia' => 169,
            ),
            65 => 
            array (
                'id' => 1949,
                'tematik_id' => 13,
                'kelompok' => 'Target',
                'nakes' => 112,
                'petugas_publik' => 200,
                'lansia' => 208,
                'masyarakat_umum' => 1190,
                'remaja' => 200,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 69,
                'usia' => 200,
            ),
            66 => 
            array (
                'id' => 1950,
                'tematik_id' => 13,
                'kelompok' => 'Target',
                'nakes' => 129,
                'petugas_publik' => 469,
                'lansia' => 262,
                'masyarakat_umum' => 1526,
                'remaja' => 469,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 62,
                'usia' => 469,
            ),
            67 => 
            array (
                'id' => 1951,
                'tematik_id' => 13,
                'kelompok' => 'Target',
                'nakes' => 115,
                'petugas_publik' => 236,
                'lansia' => 208,
                'masyarakat_umum' => 1190,
                'remaja' => 236,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 60,
                'usia' => 236,
            ),
            68 => 
            array (
                'id' => 1952,
                'tematik_id' => 13,
                'kelompok' => 'Target',
                'nakes' => 98,
                'petugas_publik' => 166,
                'lansia' => 208,
                'masyarakat_umum' => 1190,
                'remaja' => 166,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 64,
                'usia' => 166,
            ),
            69 => 
            array (
                'id' => 1953,
                'tematik_id' => 14,
                'kelompok' => 'Target',
                'nakes' => 27,
                'petugas_publik' => 214,
                'lansia' => 122,
                'masyarakat_umum' => 1587,
                'remaja' => 333,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 78,
                'usia' => 333,
            ),
            70 => 
            array (
                'id' => 1954,
                'tematik_id' => 14,
                'kelompok' => 'Target',
                'nakes' => 9,
                'petugas_publik' => 138,
                'lansia' => 122,
                'masyarakat_umum' => 1587,
                'remaja' => 333,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 83,
                'usia' => 333,
            ),
            71 => 
            array (
                'id' => 1955,
                'tematik_id' => 14,
                'kelompok' => 'Target',
                'nakes' => 14,
                'petugas_publik' => 186,
                'lansia' => 122,
                'masyarakat_umum' => 1587,
                'remaja' => 333,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 81,
                'usia' => 333,
            ),
            72 => 
            array (
                'id' => 1956,
                'tematik_id' => 14,
                'kelompok' => 'Target',
                'nakes' => 17,
                'petugas_publik' => 201,
                'lansia' => 122,
                'masyarakat_umum' => 1587,
                'remaja' => 333,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 80,
                'usia' => 333,
            ),
            73 => 
            array (
                'id' => 1957,
                'tematik_id' => 14,
                'kelompok' => 'Target',
                'nakes' => 30,
                'petugas_publik' => 236,
                'lansia' => 123,
                'masyarakat_umum' => 1587,
                'remaja' => 334,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 84,
                'usia' => 334,
            ),
            74 => 
            array (
                'id' => 1958,
                'tematik_id' => 14,
                'kelompok' => 'Target',
                'nakes' => 24,
                'petugas_publik' => 238,
                'lansia' => 122,
                'masyarakat_umum' => 1587,
                'remaja' => 333,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 79,
                'usia' => 333,
            ),
            75 => 
            array (
                'id' => 1959,
                'tematik_id' => 14,
                'kelompok' => 'Target',
                'nakes' => 40,
                'petugas_publik' => 227,
                'lansia' => 123,
                'masyarakat_umum' => 1587,
                'remaja' => 334,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 85,
                'usia' => 334,
            ),
            76 => 
            array (
                'id' => 1960,
                'tematik_id' => 14,
                'kelompok' => 'Target',
                'nakes' => 34,
                'petugas_publik' => 270,
                'lansia' => 122,
                'masyarakat_umum' => 1587,
                'remaja' => 334,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 77,
                'usia' => 334,
            ),
            77 => 
            array (
                'id' => 1961,
                'tematik_id' => 14,
                'kelompok' => 'Target',
                'nakes' => 23,
                'petugas_publik' => 190,
                'lansia' => 122,
                'masyarakat_umum' => 1587,
                'remaja' => 333,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 76,
                'usia' => 333,
            ),
            78 => 
            array (
                'id' => 1962,
                'tematik_id' => 15,
                'kelompok' => 'Target',
                'nakes' => 10,
                'petugas_publik' => 65,
                'lansia' => 29,
                'masyarakat_umum' => 665,
                'remaja' => 137,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 95,
                'usia' => 137,
            ),
            79 => 
            array (
                'id' => 1963,
                'tematik_id' => 15,
                'kelompok' => 'Target',
                'nakes' => 5,
                'petugas_publik' => 27,
                'lansia' => 32,
                'masyarakat_umum' => 197,
                'remaja' => 48,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 93,
                'usia' => 48,
            ),
            80 => 
            array (
                'id' => 1964,
                'tematik_id' => 15,
                'kelompok' => 'Target',
                'nakes' => 7,
                'petugas_publik' => 87,
                'lansia' => 57,
                'masyarakat_umum' => 998,
                'remaja' => 193,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 89,
                'usia' => 193,
            ),
            81 => 
            array (
                'id' => 1965,
                'tematik_id' => 15,
                'kelompok' => 'Target',
                'nakes' => 8,
                'petugas_publik' => 81,
                'lansia' => 58,
                'masyarakat_umum' => 876,
                'remaja' => 210,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 92,
                'usia' => 210,
            ),
            82 => 
            array (
                'id' => 1966,
                'tematik_id' => 15,
                'kelompok' => 'Target',
                'nakes' => 3,
                'petugas_publik' => 54,
                'lansia' => 60,
                'masyarakat_umum' => 1075,
                'remaja' => 250,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 91,
                'usia' => 250,
            ),
            83 => 
            array (
                'id' => 1967,
                'tematik_id' => 15,
                'kelompok' => 'Target',
                'nakes' => 9,
                'petugas_publik' => 65,
                'lansia' => 63,
                'masyarakat_umum' => 1167,
                'remaja' => 190,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 86,
                'usia' => 190,
            ),
            84 => 
            array (
                'id' => 1968,
                'tematik_id' => 15,
                'kelompok' => 'Target',
                'nakes' => 6,
                'petugas_publik' => 50,
                'lansia' => 44,
                'masyarakat_umum' => 988,
                'remaja' => 212,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 88,
                'usia' => 212,
            ),
            85 => 
            array (
                'id' => 1969,
                'tematik_id' => 15,
                'kelompok' => 'Target',
                'nakes' => 5,
                'petugas_publik' => 68,
                'lansia' => 47,
                'masyarakat_umum' => 967,
                'remaja' => 220,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 87,
                'usia' => 220,
            ),
            86 => 
            array (
                'id' => 1970,
                'tematik_id' => 15,
                'kelompok' => 'Target',
                'nakes' => 17,
                'petugas_publik' => 93,
                'lansia' => 69,
                'masyarakat_umum' => 2589,
                'remaja' => 540,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-01',
                'desa_id' => 90,
                'usia' => 540,
            ),
            87 => 
            array (
                'id' => 1972,
                'tematik_id' => 7,
                'kelompok' => 'Dosis 1',
                'nakes' => 60,
                'petugas_publik' => 115,
                'lansia' => 20,
                'masyarakat_umum' => 222,
                'remaja' => 42,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-04',
                'desa_id' => 7,
                'usia' => 37,
            ),
            88 => 
            array (
                'id' => 1973,
                'tematik_id' => 7,
                'kelompok' => 'Dosis 1',
                'nakes' => 61,
                'petugas_publik' => 115,
                'lansia' => 20,
                'masyarakat_umum' => 222,
                'remaja' => 42,
                'created_at' => NULL,
                'updated_at' => NULL,
                'tanggal' => '2022-01-05',
                'desa_id' => 7,
                'usia' => 37,
            ),
            89 => 
            array (
                'id' => 1974,
                'tematik_id' => 7,
                'kelompok' => 'Dosis 1',
                'nakes' => 64,
                'petugas_publik' => 115,
                'lansia' => 20,
                'masyarakat_umum' => 222,
                'remaja' => 42,
                'created_at' => NULL,
                'updated_at' => '2022-05-19 06:47:38',
                'tanggal' => '2022-01-06',
                'desa_id' => 7,
                'usia' => 37,
            ),
        ));
        
        
    }
}